<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>Dialog</name>
    <message>
        <source>Über Lokkat</source>
        <translation>About Lokkat</translation>
    </message>
    <message>
        <source>Lokkat v0.5 Private Beta</source>
        <translation type="vanished">Lokkat v0.5 Private Beta</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Danke, dass du Lokkat nutzt. Lokkat ist &lt;a href=&quot;https://de.wikipedia.org/wiki/Freie_Software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;freie Software&lt;/span&gt;&lt;/a&gt; und unter der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt; lizensiert. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Das Ziel bei der Entwicklung dieser Anwendung war es, der Öffentlichkeit eine einfach nutzbare, kostenfreie und quelloffene Möglichkeit zu bieten, die starke &lt;a href=&quot;https://de.wikipedia.org/wiki/One-Time-Pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP-Verschlüsselung&lt;/span&gt;&lt;/a&gt; zu nutzen. Ich hoffe, das habe ich erreicht.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Falls du dir den Quellcode anschauen möchtest, findest du ihn hier.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Die Projektwebseite findest du &lt;a href=&quot;http://redneptun.net/Lokkat&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir als Dankeschön einen Kaffee oder ein Bier spendieren möchtest, weil dir die Software gefällt und du so etwas unterstützen möchtest, dann klick &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den-US%26country.x%3DUS%26flowType%3Dsend&amp;amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en-US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den-US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir etwas Nettes schreiben möchtest, kannst du das &lt;a href=&quot;mailto:lokkat@redneptun.net&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt; tun.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Dieses Programm wird OHNE JEGLICHE GEWÄHRLEISTUNG bereitgestellt; Es handelt sich um freie Software und du darfst sie gern unter bestimmten Bedingungen weiterverbreiten. Mehr hierzu findest du in der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;Lizenz&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="vanished">&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Thank you for using Lokkat. Lokkat is&lt;a href=&quot;https://en.wikipedia.org/wiki/Free_software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;free software&lt;/span&gt;&lt;/a&gt; , and is licensed under the &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt;. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;My goal was to develop an application to offer a simple to use, free of charge und open source possibility to utilize the strong &lt;a href=&quot;https://en.wikipedia.org/wiki/One-time_pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP encryption&lt;/span&gt;&lt;/a&gt;. I hope, I have achieved that.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you want to see the source code, you can find it here.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;You can find the projects website &lt;a href=&quot;http://redneptun.net/lokkat&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you would like to to thank me by buying me a coffee or beer, because you like the software and want to support this and further free software projects, click &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den_US%26country.x%3DUS%26flowType%3Dsend&amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en_US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den_US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22You%2520are%2520sending%2520Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you want want to write me something nice, click &lt;a href=&quot;mailto:lokkat@redneptun.net&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt; .&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;This program comes with ABSOLUTELY NO WARRANTY; This is free software, and you are welcome to redistribute it under certain conditions; see &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;the license&lt;/span&gt;&lt;/a&gt; for details.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Danke, dass du Lokkat nutzt. Lokkat ist &lt;a href=&quot;https://de.wikipedia.org/wiki/Freie_Software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;freie Software&lt;/span&gt;&lt;/a&gt; und unter der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt; lizensiert. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Das Ziel bei der Entwicklung dieser Anwendung war es, der Öffentlichkeit eine einfach nutzbare, kostenfreie und quelloffene Möglichkeit zu bieten, die starke &lt;a href=&quot;https://de.wikipedia.org/wiki/One-Time-Pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP-Verschlüsselung&lt;/span&gt;&lt;/a&gt; zu nutzen. Ich hoffe, das habe ich erreicht.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Falls du dir den Quellcode anschauen möchtest, findest du ihn hier.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Die Projektwebseite findest du &lt;a href=&quot;http://redneptun.net/Lokkat&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir als Dankeschön einen Kaffee oder ein Bier spendieren möchtest, weil dir die Software gefällt und du so etwas unterstützen möchtest, dann klick &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den-US%26country.x%3DUS%26flowType%3Dsend&amp;amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en-US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den-US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir etwas Nettes schreiben möchtest, kannst du das &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den-US%26country.x%3DUS%26flowType%3Dsend&amp;amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en-US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den-US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt; tun.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Dieses Programm wird OHNE JEGLICHE GEWÄHRLEISTUNG bereitgestellt; Es handelt sich um freie Software und du darfst sie gern unter bestimmten Bedingungen weiterverbreiten. Mehr hierzu findest du in der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;Lizenz&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="vanished">&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Thank you for using Lokkat. Lokkat is&lt;a href=&quot;https://en.wikipedia.org/wiki/Free_software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;free software&lt;/span&gt;&lt;/a&gt; , and is licensed under the &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt;. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;My goal was to develop an application to offer the public a simple to use, free of charge und open source possibility to utilize the strong &lt;a href=&quot;https://en.wikipedia.org/wiki/One-time_pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP encryption&lt;/span&gt;&lt;/a&gt;. I hope, I have achieved that.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you wanf to see the source code, you can find it here.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;You can find the projects website &lt;a href=&quot;http://redneptun.net/Lokkat_en&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you would like to to thank me by buying me a coffee or beer, because you like the software and want to support this and further free software projects, click &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den_US%26country.x%3DUS%26flowType%3Dsend&amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en_US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den_US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22You%2520are%2520sending%2520Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you want want to write me something nice, click &lt;a href=&quot;mailto:admin@redneptun.net&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt; .&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;his program comes with ABSOLUTELY NO WARRANTY; This is free software, and you are welcome to redistribute it under certain conditions; see &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;the license&lt;/span&gt;&lt;/a&gt; for details.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Danke, dass du Lokkat nutzt. Lokkat ist &lt;a href=&quot;https://de.wikipedia.org/wiki/Freie_Software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;freie Software&lt;/span&gt;&lt;/a&gt; und unter der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt; lizensiert. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Das Ziel bei der Entwicklung dieser Anwendung war es, der Öffentlichkeit eine einfach nutzbare, kostenfreie und quelloffene Möglichkeit zu bieten, die starke &lt;a href=&quot;https://de.wikipedia.org/wiki/One-Time-Pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP-Verschlüsselung&lt;/span&gt;&lt;/a&gt; zu nutzen. Ich hoffe, das habe ich erreicht.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Falls du dir den Quellcode anschauen möchtest, findest du ihn hier.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Die Projektwebseite findest du &lt;a href=&quot;http://redneptun.net/Lokkat&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir als Dankeschön einen Kaffee oder ein Bier spendieren möchtest, weil dir die Software gefällt und du so etwas unterstützen möchtest, dann klick &lt;a href=&quot;https://www.paypal.com/myaccount/transfer/send/preview&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir etwas Nettes schreiben möchtest, kannst du das &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den-US%26country.x%3DUS%26flowType%3Dsend&amp;amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en-US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den-US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt; tun.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Dieses Programm wird OHNE JEGLICHE GEWÄHRLEISTUNG bereitgestellt; Es handelt sich um freie Software und du darfst sie gern unter bestimmten Bedingungen weiterverbreiten. Mehr hierzu findest du in der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;Lizenz&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="vanished">&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Thank you for using Lokkat. Lokkat is&lt;a href=&quot;https://en.wikipedia.org/wiki/Free_software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;free software&lt;/span&gt;&lt;/a&gt; , and is licensed under the &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt;. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;My goal was to develop an application to offer the public a simple to use, free of charge und open source possibility to utilize the strong &lt;a href=&quot;https://en.wikipedia.org/wiki/One-time_pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP encryption&lt;/span&gt;&lt;/a&gt;. I hope, I have achieved that.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you wanf to see the source code, you can find it here.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;You can find the projects website &lt;a href=&quot;http://redneptun.net/Lokkat_en&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you would like to to thank me by buying me a coffee or beer, because you like the software and want to support this and further free software projects, click &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den_US%26country.x%3DUS%26flowType%3Dsend&amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en_US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den_US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22You%2520are%2520sending%2520Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you want want to write me something nice, click &lt;a href=&quot;mailto:admin@redneptun.net&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt; .&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;his program comes with ABSOLUTELY NO WARRANTY; This is free software, and you are welcome to redistribute it under certain conditions; see &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;the license&lt;/span&gt;&lt;/a&gt; for details.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Danke, dass du Lokkat nutzt. Lokkat ist &lt;a href=&quot;https://de.wikipedia.org/wiki/Freie_Software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;freie Software&lt;/span&gt;&lt;/a&gt; , und unter der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt; lizensiert. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Das Ziel bei der Entwicklung dieser Anwendung war es, der Öffentlichkeit eine einfach nutzbare, kostenfreie und quelloffene Möglichkeit zu bieten, die starke &lt;a href=&quot;https://de.wikipedia.org/wiki/One-Time-Pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP-Verschlüsselung&lt;/span&gt;&lt;/a&gt; zu nutzen. Ich hoffe, das habe ich erreicht.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Falls du dir den Quellcode anschauen möchtest, findest du ihn hier.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Die Projektwebseite findest du &lt;a href=&quot;http://redneptun.net/Lokkat&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir als Dankeschön einen Kaffee oder Bier spendieren möchtest, weil dir die Software gefällt und so etwas unterstützen möchtest, dann klick &lt;a href=&quot;https://www.paypal.com/myaccount/transfer/send/preview&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir etwas Nettes schreiben möchtest, kannst du das &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den-US%26country.x%3DUS%26flowType%3Dsend&amp;amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en-US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den-US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt; tun.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Dieses Programm wird OHNE JEGLICHE GARANTIE bereitgestellt; Es handelt sich um freie Software und du darfst sie gern unter bestimmten Bedingungen weiterverbreiten. Mehr hierzu findest du in der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;Lizenz&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="vanished">&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Thank you for using Lokkat. Lokkat is&lt;a href=&quot;https://en.wikipedia.org/wiki/Free_software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;free software&lt;/span&gt;&lt;/a&gt; , and is licensed under the &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt;. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;My goal was to develop an application to offer the public a simple to use, free of charge und open source possibility to utilize the strong &lt;a href=&quot;https://en.wikipedia.org/wiki/One-time_pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP encryption&lt;/span&gt;&lt;/a&gt;. I hope, I have achieved that.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you wanf to see the source code, you can find it here.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;You can find the projects website &lt;a href=&quot;http://redneptun.net/Lokkat_en&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you would like to to thank me by buying me a coffee or beer, because you like the software and want to support this and further free software projects, click &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den_US%26country.x%3DUS%26flowType%3Dsend&amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en_US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den_US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22You%2520are%2520sending%2520Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you want want to write me something nice, click &lt;a href=&quot;mailto:admin@redneptun.net&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt; .&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;his program comes with ABSOLUTELY NO WARRANTY; This is free software, and you are welcome to redistribute it under certain conditions; see &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;the license&lt;/span&gt;&lt;/a&gt; for details.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Danke, dass du Lokkat nutzt. Lokkat ist &lt;a href=&quot;https://de.wikipedia.org/wiki/Freie_Software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;freie Software&lt;/span&gt;&lt;/a&gt; , und unter der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt; lizensiert. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Das Ziel bei der Entwicklung dieser Anwendung war es, der Öffentlichkeit eine einfach nutzbare, kostenfreie und quelloffene Möglichkeit zu bieten, die starke &lt;a href=&quot;https://de.wikipedia.org/wiki/One-Time-Pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP-Verschlüsselung&lt;/span&gt;&lt;/a&gt; zu nutzen. Ich hoffe, das habe ich erreicht.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Falls du dir den Quellcode anschauen möchtest, findest du ihn hier.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Die Projektwebseite findest du &lt;a href=&quot;http://redneptun.net/Lokkat&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir als Dankeschön einen Kaffee oder Bier spendieren möchtest, weil dir die Software gefällt und so etwas unterstützen möchtest, dann klick &lt;a href=&quot;https://www.paypal.com/myaccount/transfer/send/preview&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir etwas Nettes schreiben möchtest, kannst du das &lt;a href=&quot;mailto:admin@redneptun.net&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt; tun.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Dieses Programm wird OHNE JEGLICHE GARANTIE bereitgestellt; Es handelt sich um freie Software und du darfst sie gern unter bestimmten Bedingungen weiterverbreiten. Mehr hierzu findest du in der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;Lizenz&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="vanished">&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Thank you for using Lokkat. Lokkat is&lt;a href=&quot;https://en.wikipedia.org/wiki/Free_software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;free software&lt;/span&gt;&lt;/a&gt; , and is licensed under the &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt;. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;My goal was to develop an application to offer the public a simple to use, free of charge und open source possibility to utilize the strong &lt;a href=&quot;https://en.wikipedia.org/wiki/One-time_pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP encryption&lt;/span&gt;&lt;/a&gt;. I hope, I have achieved that.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you wanf to see the source code, you can find it here.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;You can find the projects website &lt;a href=&quot;http://redneptun.net/Lokkat_en&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you would like to to thank me by buying me a coffee or beer, because you like the software and want to support this and further free software projects, click &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den_US%26country.x%3DUS%26flowType%3Dsend&amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en_US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den_US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22You%2520are%2520sending%2520Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you want want to write me something nice, click &lt;a href=&quot;mailto:admin@redneptun.net&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt; .&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;his program comes with ABSOLUTELY NO WARRANTY; This is free software, and you are welcome to redistribute it under certain conditions; see &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;the license&lt;/span&gt;&lt;/a&gt; for details.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <source>nya!</source>
        <translation>nya!</translation>
    </message>
    <message>
        <source>...Katzen können sehr verschwiegen sein, nya!</source>
        <translation>...cats can be very secretive, nya!</translation>
    </message>
    <message>
        <source>Lokkat v0.5 Closed Beta</source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Danke, dass du Lokkat nutzt. Lokkat ist &lt;a href=&quot;https://de.wikipedia.org/wiki/Freie_Software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;freie Software&lt;/span&gt;&lt;/a&gt; und unter der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt; lizensiert. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Das Ziel bei der Entwicklung dieser Anwendung war es, der Öffentlichkeit eine einfach nutzbare, kostenfreie und quelloffene Möglichkeit zu bieten, die starke &lt;a href=&quot;https://de.wikipedia.org/wiki/One-Time-Pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP-Verschlüsselung&lt;/span&gt;&lt;/a&gt; zu nutzen. Ich hoffe, das habe ich erreicht.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Falls du dir den Quellcode anschauen möchtest, findest du ihn &lt;a href=&quot;https://github.com/redneptun/lokkat&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Die Projektwebseite findest du &lt;a href=&quot;http://redneptun.net/Lokkat&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir als Dankeschön einen Kaffee oder ein Bier spendieren möchtest, weil dir die Software gefällt und du so etwas unterstützen möchtest, dann klick &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den-US%26country.x%3DUS%26flowType%3Dsend&amp;amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en-US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den-US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Wenn du mir etwas Nettes schreiben möchtest, kannst du das &lt;a href=&quot;mailto:lokkat@redneptun.net&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt; tun.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Dieses Programm wird OHNE JEGLICHE GEWÄHRLEISTUNG bereitgestellt; Es handelt sich um freie Software und du darfst sie gern unter bestimmten Bedingungen weiterverbreiten. Mehr hierzu findest du in der &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;Lizenz&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;Noto Sans&apos;; font-size:9pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Thank you for using Lokkat. Lokkat is &lt;a href=&quot;https://en.wikipedia.org/wiki/Free_software&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;free software&lt;/span&gt;&lt;/a&gt; and is licensed under the &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;GNU Public License v3&lt;/span&gt;&lt;/a&gt;. &lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;My goal was to develop an application to offer a simple to use, free of charge und open source possibility to utilize the strong &lt;a href=&quot;https://en.wikipedia.org/wiki/One-time_pad&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;OTP encryption&lt;/span&gt;&lt;/a&gt; to the public . I hope, I have achieved that.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you want to see the source code, you can find it &lt;a href=&quot;https://github.com/redneptun/lokkat&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;hier&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;You can find the projects website &lt;a href=&quot;http://redneptun.net/lokkat&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you would like to to thank me by buying me a coffee or beer, because you like the software and want to support this and further free software projects, click &lt;a href=&quot;https://www.paypal.com/signin?returnUri=https://www.paypal.com/myaccount/transfer/send/external/ppme?profile%3Dredneptun%26currencyCode%3DEUR%26amount%3D3.5%26locale.x%3Den-US%26country.x%3DUS%26flowType%3Dsend&amp;amp;onboardData=%7B%22country.x%22%3A%22US%22%2C%22locale.x%22%3A%22en-US%22%2C%22intent%22%3A%22paypalme%22%2C%22redirect_url%22%3A%22https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Ftransfer%2Fsend%2Fexternal%2Fppme%3Fprofile%253Dredneptun%2526currencyCode%253DEUR%2526amount%253D3.5%2526locale.x%253Den-US%2526country.x%253DUS%2526flowType%253Dsend%22%2C%22sendMoneyText%22%3A%22Philipp%2520B%25C3%25B6ckmann%2520%25E2%2582%25AC3.50%22%7D&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt;.&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;If you want want to write me something nice, click &lt;a href=&quot;mailto:lokkat@redneptun.net&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;here&lt;/span&gt;&lt;/a&gt; .&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;Lokkat Copyright © 2019 Philipp Böckmann&lt;/p&gt;
&lt;p style=&quot; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;This program comes with ABSOLUTELY NO WARRANTY; This is free software, and you are welcome to redistribute it under certain conditions; see &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.en.html&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#0000ff;&quot;&gt;the license&lt;/span&gt;&lt;/a&gt; for details.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
</context>
</TS>
