#!/bin/bash

rm pak/gnu_linux/*.tar.*
mkdir pak/gnu_linux

# make the dist
./make_dist_gnu_linux










# build the portable tar.gz
(cd dist/gnu_linux && tar -cavf ../../pak/gnu_linux/Lokkat-0.5.tar.gz *)