# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/report_bug.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_report_bug(object):
    def setupUi(self, report_bug):
        report_bug.setObjectName("report_bug")
        report_bug.setWindowModality(QtCore.Qt.ApplicationModal)
        report_bug.resize(669, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        report_bug.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(report_bug)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(report_bug)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblName = QtWidgets.QLabel(self.page)
        self.lblName.setObjectName("lblName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblName)
        self.txtName = QtWidgets.QLineEdit(self.page)
        self.txtName.setObjectName("txtName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtName)
        self.lblEmail = QtWidgets.QLabel(self.page)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblEmail)
        self.txtMail = QtWidgets.QLineEdit(self.page)
        self.txtMail.setObjectName("txtMail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtMail)
        self.lblTitle = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblTitle)
        self.txtTitle = QtWidgets.QLineEdit(self.page)
        self.txtTitle.setObjectName("txtTitle")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtTitle)
        self.lblDescription = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDescription.setFont(font)
        self.lblDescription.setObjectName("lblDescription")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblDescription)
        self.txtDescription = QtWidgets.QTextEdit(self.page)
        self.txtDescription.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.txtDescription.setAcceptRichText(False)
        self.txtDescription.setObjectName("txtDescription")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtDescription)
        self.lblInfo = QtWidgets.QLabel(self.page)
        self.lblInfo.setMinimumSize(QtCore.QSize(0, 0))
        self.lblInfo.setLineWidth(1)
        self.lblInfo.setTextFormat(QtCore.Qt.RichText)
        self.lblInfo.setWordWrap(True)
        self.lblInfo.setOpenExternalLinks(True)
        self.lblInfo.setObjectName("lblInfo")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lblInfo)
        self.btnSend = QtWidgets.QPushButton(self.page)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/mail_yellow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSend.setIcon(icon1)
        self.btnSend.setObjectName("btnSend")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btnSend)
        self.lblInfo_2 = QtWidgets.QLabel(self.page)
        self.lblInfo_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lblInfo_2.setLineWidth(1)
        self.lblInfo_2.setTextFormat(QtCore.Qt.RichText)
        self.lblInfo_2.setWordWrap(True)
        self.lblInfo_2.setOpenExternalLinks(True)
        self.lblInfo_2.setObjectName("lblInfo_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblInfo_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.trError = QtWidgets.QLabel(self.page_2)
        self.trError.setGeometry(QtCore.QRect(10, 10, 54, 17))
        self.trError.setObjectName("trError")
        self.trInvalidMail = QtWidgets.QLabel(self.page_2)
        self.trInvalidMail.setGeometry(QtCore.QRect(10, 30, 341, 17))
        self.trInvalidMail.setObjectName("trInvalidMail")
        self.trSuccess = QtWidgets.QLabel(self.page_2)
        self.trSuccess.setGeometry(QtCore.QRect(10, 50, 341, 17))
        self.trSuccess.setObjectName("trSuccess")
        self.trSuccessLink = QtWidgets.QLabel(self.page_2)
        self.trSuccessLink.setGeometry(QtCore.QRect(10, 70, 391, 17))
        self.trSuccessLink.setObjectName("trSuccessLink")
        self.trFailureText = QtWidgets.QLabel(self.page_2)
        self.trFailureText.setGeometry(QtCore.QRect(10, 90, 611, 17))
        self.trFailureText.setObjectName("trFailureText")
        self.trInvalidTitle = QtWidgets.QLabel(self.page_2)
        self.trInvalidTitle.setGeometry(QtCore.QRect(10, 110, 611, 17))
        self.trInvalidTitle.setObjectName("trInvalidTitle")
        self.trInvalidDescription = QtWidgets.QLabel(self.page_2)
        self.trInvalidDescription.setGeometry(QtCore.QRect(10, 130, 611, 17))
        self.trInvalidDescription.setObjectName("trInvalidDescription")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)

        self.retranslateUi(report_bug)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(report_bug)

    def retranslateUi(self, report_bug):
        _translate = QtCore.QCoreApplication.translate
        report_bug.setWindowTitle(_translate("report_bug", "Fehlerbericht senden"))
        self.lblName.setText(_translate("report_bug", "Name (optional):"))
        self.lblEmail.setText(_translate("report_bug", "E-Mail (optional):"))
        self.lblTitle.setText(_translate("report_bug", "Titel:"))
        self.lblDescription.setText(_translate("report_bug", "Fehlerbeschreibung:"))
        self.lblInfo.setText(_translate("report_bug", "Mit einem Klick auf \"Absenden\" wird aus deinen Einträgen ein sog. \"Issue\" auf der Quellcodeverwaltungsseite von Lokkat bei Github erstellt. Dieses Issue kann dann Entwicklern bearbeitet und (hoffentlich) gelöst werden."))
        self.btnSend.setText(_translate("report_bug", "Absenden"))
        self.lblInfo_2.setText(_translate("report_bug", "Trage deine E-Mailadresse nur ein, wenn du mit Rückfragen rechnest und es dir egal ist, dass sie im öffentlichen Repository von Lokkat auf Github angezeigt wird und somit öffentlich sichtbar ist."))
        self.trError.setText(_translate("report_bug", "Fehler"))
        self.trInvalidMail.setText(_translate("report_bug", "Ungültige E-Mailadresse. Vielleicht hast du dich vertippt?"))
        self.trSuccess.setText(_translate("report_bug", "Problem erfolgreich gemeldet"))
        self.trSuccessLink.setText(_translate("report_bug", "Du kannst den Status deines gemeldeten Problems hier einsehen: {}"))
        self.trFailureText.setText(_translate("report_bug", "Der Fehlerbericht konnte leider nicht automatisiert versendet werden. Sieht so aus, als läge hier noch mehr im Argen. Schreibst du bitte eine E-Mail an lokkat@redneptun.net? Danke."))
        self.trInvalidTitle.setText(_translate("report_bug", "Trag bitte einen Titel ein, der zu deiner Problemmeldung passt."))
        self.trInvalidDescription.setText(_translate("report_bug", "Das Beschreibungsfeld darf nicht leer sein."))
from gui import resources_rc
